version: "3"
services:
  es:
    image: elasticsearch:8.3.3
  web:
    image: delkabo/foodtrucks-web
    command: python3 app.py
    depends_on:
      - es
    ports:
      - 5000:5000
    volumes:
      - .:/code
