- name: Ping Servers
  hosts: all
  become: yes

  tasks:

  - name: Task ping
    ping:

  - name: install apache2
    apt:
      pkg: apache2
      state: present

  - name: copy File
    copy:
      src: ./fansible1
      dest: /home/
      mode: 0777
